---
functional:
  - На странице товара и в каталоге нужно выводить название, рейтинг, цена со скидкой и без нее
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность добавлять товар в корзину и продолжать выбирать товары в каталоге
  - На странице корзины пользователь cможет удалить товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты. 
non-functional:
  - Нужно разработать интерфейс интернет-магазина с просмотром и фильтрацией товаров, а также добавлением их в корзину
  - Ключевой возможностью магазина будет адаптивная верстка, чтобы он был удобным на мобильных устройствах
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть доступен на различных устройствах
  - Магазин будет SPA-приложение, которое не перезагружает страницу. Пользователь будет просматривать каталог товаров, фильтруя их и пользуясь постраничным выводом
  - Корзина будет хранится в сессии браузера
implicit:
  - Пользователь должен иметь возможность очистить всю корзину
  - Сайт должен быть мультиязычным
  - Консоль не должна содержать ошибок
  - Хештег на странице с товаром должен переносить пользователя в соответствующую категорию 
  - Пользователь должен иметь возможность закрыть страницу с оформлением заказа