---
functional:
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
non-functional:
  - На странице товара и в каталоге нужно выводить название, рейтинг, цена со скидкой и без нее
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть доступен на различных устройствах
implicit:
  - На сайте нужно разработать интерфейс магазина с просмотром фильтрацией товаров, а так же добавлением их в корзину
  - Сайт должен быть SPA приложением которое не перезагружает страницу. 
  - Пользователь должен иметь возможность удалить товар из корзины и очистить всю корзину
  - Пользователь должен иметь возможность оформлять заказ с переходом на страницу оплаты
  - Корзина должна храниться в сессии браузера.
  - Пользователь должен иметь возможность добавлять товар в корзину и продолжать выбирать товары в каталоге
  - Пользователь должен иметь возможность пользоваться постраничным выводом
  - Сайт должен быть мультиязычным
  - Консоль не должна содержать ошибок
  - Хештег на странице с товаром должен переносить пользователя в соответствующую категорию 
  - Пользователь должен иметь возможность закрыть страницу с оформлением заказа